## Competing-risks stacked-EE sandwich: cross-validation against an independent
## delicatessen M-estimation oracle, influence-function sanity, CIF-difference /
## CIF-ratio CI coverage, and the sandwich-vs-bootstrap agreement that guards
## the all-cause (1 - H) sensitivity denominator.

test_that("CR sandwich matches the delicatessen oracle on shared data", {
  ## The R fit and the Python delicatessen stack read the SAME person-period
  ## fixture (id, t, A, L, event, at_risk). The committed CSV is regenerated by
  ## data-raw/delicatessen_competing_risks.py; the design is ~factor(t)+A+L,
  ## matching the Python build_design(). Point + SE agree to ~1e-4.
  data_path <- test_path("fixtures", "python", "cr_survival_data.csv")
  ref_path <- test_path("fixtures", "python", "cr_survival_delicatessen.csv")
  skip_if(!file.exists(ref_path))

  df <- data.table::fread(data_path)
  deli <- data.table::fread(ref_path)
  fit <- surv_fit(
    df,
    outcome = "event",
    treatment = "A",
    confounders = ~L,
    id = "id",
    time = "t",
    competing = "event",
    time_formula = ~ factor(t)
  )
  ivs <- list(a1 = causatr::static(1), a0 = causatr::static(0))
  tms <- c(2L, 4L)
  cif <- contrast(
    fit,
    ivs,
    times = tms,
    type = "cif",
    cause = c(1L, 2L),
    ci_method = "sandwich"
  )
  rd <- suppressMessages(contrast(
    fit,
    ivs,
    times = tms,
    type = "cif_difference",
    cause = c(1L, 2L),
    ci_method = "sandwich"
  ))
  sv <- contrast(
    fit,
    ivs,
    times = tms,
    type = "survival",
    ci_method = "sandwich"
  )

  ## Compare each delicatessen quantity to its survatr counterpart.
  get_one <- function(q, t) {
    if (grepl("^F", q)) {
      j <- as.integer(substr(q, 2L, 2L))
      a <- sub("^F\\d_", "", q) # arm label, a1 or a0
      r <- cif$estimates[
        get("intervention") == a & get("cause") == j & get("time") == t
      ]
      return(c(r$cif_hat, r$se))
    }
    if (grepl("^S_", q)) {
      a <- sub("^S_", "", q)
      r <- sv$estimates[get("intervention") == a & get("time") == t]
      return(c(r$s_hat, r$se))
    }
    ## RDj: survatr "a0 vs a1" = F_a0 - F_a1.
    j <- as.integer(sub("^RD", "", q))
    r <- rd$contrasts[get("cause") == j & get("time") == t]
    c(r$estimate, r$se)
  }
  for (i in seq_len(nrow(deli))) {
    sv_vals <- get_one(deli$quantity[i], deli$time[i])
    expect_equal(sv_vals[1L], deli$estimate[i], tolerance = 1e-3)
    expect_equal(sv_vals[2L], deli$se[i], tolerance = 1e-3)
  }
})

test_that("the per-time row guard returns one row per id per time", {
  ## Defensive parity with the single-event `compute_survival_if_matrix()`
  ## guard. Track A PP is rectangular so the public path never trips this, but a
  ## future ragged-PP / left-truncation path must abort loudly rather than
  ## `colMeans` over the wrong row set.
  ## A valid (id, time) layout: 3 ids x 2 times -> 3 rows at each time.
  t_ok <- c(1L, 2L, 1L, 2L, 1L, 2L)
  rows <- cr_rows_by_time(t_ok, times = c(1L, 2L), n_ids = 3L)
  expect_length(rows, 2L)
  expect_identical(lengths(rows), c(3L, 3L))
})

test_that("the per-time row guard aborts on a length mismatch", {
  ## time 2 has only 2 rows but n_ids = 3 -> classed abort.
  t_bad <- c(1L, 2L, 1L, 2L, 1L)
  expect_error(
    cr_rows_by_time(t_bad, times = c(1L, 2L), n_ids = 3L),
    class = "survatr_if_failed"
  )
})

test_that("per-cause CIF influence-function columns have mean ~ 0", {
  pp <- sim_two_cause_constant_hazard(
    n = 2000L,
    K = 5L,
    seed = 31L,
    beta1_A = -0.4,
    beta1_L = 0.5,
    gamma = 0.5
  )
  fit <- surv_fit(
    pp,
    outcome = "event",
    treatment = "A",
    confounders = ~L,
    id = "id",
    time = "t",
    competing = "event",
    time_formula = ~ factor(t)
  )
  shared <- prepare_cr_sandwich_shared(fit)
  pieces <- cr_intervention_if_pieces(fit, causatr::static(1), shared)
  ifm <- compute_cif_if_matrix(pieces, cause_j = 1L, times = c(2L, 4L))
  ## A correctly centred influence function averages to ~0 across individuals.
  expect_equal(colMeans(ifm$IF_mat), c(0, 0), tolerance = 1e-8)
  ## And the all-cause survival IF too.
  ifs <- compute_cr_survival_if_matrix(pieces, times = c(2L, 4L))
  expect_equal(colMeans(ifs$IF_mat), c(0, 0), tolerance = 1e-8)
})

test_that("CR sandwich SE tracks the bootstrap SE", {
  skip_on_cran()
  pp <- sim_two_cause_constant_hazard(
    n = 1200L,
    K = 5L,
    seed = 42L,
    beta1_A = -0.4,
    beta1_L = 0.5,
    beta2_L = 0.3,
    gamma = 0.6
  )
  fit <- surv_fit(
    pp,
    outcome = "event",
    treatment = "A",
    confounders = ~L,
    id = "id",
    time = "t",
    competing = "event",
    time_formula = ~ factor(t)
  )
  ivs <- list(a1 = causatr::static(1), a0 = causatr::static(0))
  tms <- c(2L, 4L)
  sw <- suppressMessages(contrast(
    fit,
    ivs,
    times = tms,
    type = "cif_difference",
    cause = 1L,
    ci_method = "sandwich"
  ))
  bt <- suppressMessages(contrast(
    fit,
    ivs,
    times = tms,
    type = "cif_difference",
    cause = 1L,
    ci_method = "bootstrap",
    n_boot = 300L,
    seed = 7L
  ))
  m <- merge(
    sw$contrasts[, c("time", "se")],
    bt$contrasts[, c("time", "se")],
    by = "time",
    suffixes = c("_sw", "_bt")
  )
  expect_equal(m$se_sw, m$se_bt, tolerance = 0.2)
})

test_that("CIF-difference CI covers 0 under a no-effect DGP", {
  skip_on_cran()
  ## No treatment effect on either cause: the cause-1 CIF difference is truly 0,
  ## so a calibrated 95% CI should cover 0 in ~95% of replicates.
  times <- c(2L, 4L)
  n_rep <- 150L
  covers <- matrix(FALSE, n_rep, length(times))
  for (r in seq_len(n_rep)) {
    pp <- sim_two_cause_constant_hazard(
      n = 600L,
      K = 4L,
      h1 = 0.10,
      h2 = 0.07,
      seed = 1000L + r,
      gamma = 0.5,
      beta1_L = 0.5,
      beta2_L = 0.3
    )
    fit <- surv_fit(
      pp,
      outcome = "event",
      treatment = "A",
      confounders = ~L,
      id = "id",
      time = "t",
      competing = "event",
      time_formula = ~ factor(t)
    )
    res <- suppressMessages(contrast(
      fit,
      interventions = list(a1 = causatr::static(1), a0 = causatr::static(0)),
      times = times,
      type = "cif_difference",
      cause = 1L,
      ci_method = "sandwich"
    ))
    co <- res$contrasts[order(time)]
    covers[r, ] <- co$ci_lower <= 0 & co$ci_upper >= 0
  }
  cover_rate <- colMeans(covers)
  ## Allow Monte-Carlo slack on 150 reps: expect at least ~88% nominal 95%.
  expect_true(all(cover_rate >= 0.88))
})

test_that("CIF-ratio CI is strictly positive and covers 1 under no effect", {
  pp <- sim_two_cause_constant_hazard(
    n = 3000L,
    K = 4L,
    h1 = 0.10,
    h2 = 0.07,
    seed = 77L,
    gamma = 0.5,
    beta1_L = 0.5
  )
  fit <- surv_fit(
    pp,
    outcome = "event",
    treatment = "A",
    confounders = ~L,
    id = "id",
    time = "t",
    competing = "event",
    time_formula = ~ factor(t)
  )
  res <- suppressMessages(contrast(
    fit,
    interventions = list(a1 = causatr::static(1), a0 = causatr::static(0)),
    times = c(2L, 4L),
    type = "cif_ratio",
    cause = 1L,
    ci_method = "sandwich"
  ))
  expect_true(all(res$contrasts$ci_lower > 0))
  expect_true(all(res$contrasts$ci_upper > res$contrasts$ci_lower))
  expect_true(all(res$contrasts$ci_lower <= 1 & res$contrasts$ci_upper >= 1))
})

test_that("CR sandwich composes with an mgcv::gam baseline hazard", {
  skip_if_not_installed("mgcv")
  pp <- sim_two_cause_constant_hazard(
    n = 1500L,
    K = 6L,
    seed = 51L,
    beta1_A = -0.4,
    gamma = 0.4
  )
  fit <- surv_fit(
    pp,
    outcome = "event",
    treatment = "A",
    confounders = ~L,
    id = "id",
    time = "t",
    competing = "event",
    time_formula = ~ s(t, k = 4),
    model_fn = mgcv::gam
  )
  res <- suppressMessages(contrast(
    fit,
    interventions = list(a1 = causatr::static(1), a0 = causatr::static(0)),
    times = c(2L, 4L, 6L),
    type = "cif_difference",
    cause = 1L,
    ci_method = "sandwich"
  ))
  expect_false(anyNA(res$contrasts$se))
  expect_true(all(is.finite(res$contrasts$se)))
  expect_true(all(res$contrasts$se > 0))
})
