## Quiet R CMD check about data.table NSE column references.
utils::globalVariables(c(
  ".I",
  ".survatr_prev_event",
  ".survatr_prev_cens",
  ".cf_hazard",
  ".cf_surv",
  ".pseudo_y",
  ".nu",
  "intervention",
  "s_hat",
  "risk_hat",
  "rmst_hat",
  "time",
  "se",
  "ci_lower",
  "ci_upper",
  "estimate"
))
